In [1]:
import seaborn as sns
import numpy as np
import pandas as pd

In [2]:
df = pd.DataFrame(pd.read_excel("nakit_satis.xlsx"))
df.copy()
df.head()

,satisid,urunid,musteriid,barkodno,urunadi,satisadet,satisfiyati,toplamsatis,satistarihi,satistarihi2,personelid,satisnot,firmaid
0,74194,55,0,X,BARKODSUZ ÜRÜN,1,4.0,4.0,2022-11-06,2022-11-06 00:01:01,3,NaN,42.0
1,74195,4191,0,5449000189356,FUSE TEA 1 L MANGO ANANAS,1,12.5,12.5,2022-11-06,2022-11-06 00:01:11,3,NaN,12.0
2,74196,4672,0,8690504067108,ÜLKER KEKSRA JÖLEBOL ÇİLEKLİ (40G),1,3.5,3.5,2022-11-06,2022-11-06 00:01:16,3,NaN,34.0
3,74197,4171,0,8690526074238,ETİ KRAX DAHA BAHARATLI,1,4.0,4.0,2022-11-06,2022-11-06 00:01:19,3,NaN,15.0
4,74198,60,0,8690504027508,ÜLKER ÇOKANAT,1,5.0,5.0,2022-11-06,2022-11-06 00:01:22,3,NaN,34.0

In [3]:
df.shape

(46739, 13)

In [4]:
# Barkodsuz urunleri silme
df.drop(df.loc[df['barkodno']=="X"].index, inplace=True)
df.tail()

,satisid,urunid,musteriid,barkodno,urunadi,satisadet,satisfiyati,toplamsatis,satistarihi,satistarihi2,personelid,satisnot,firmaid
46734,24820,200,0,8690637878077,ALGİDA KEYİF 750 ML VİŞNE LİMON,1,20.0,20.0,2022-07-01,2022-07-01 23:49:04,1,NaN,1.0
46735,24821,4162,0,90162848,RED BUL ŞEKERSİZ 250 ML,2,15.0,30.0,2022-07-01,2022-07-01 23:55:38,1,NaN,27.0
46736,24822,623,0,86935258,MALBORA TOUCH GRAY,1,28.0,28.0,2022-07-01,2022-07-01 23:55:49,1,NaN,25.0
46737,24823,618,0,86937757,MALBORA EDGE BULUE,1,27.0,27.0,2022-07-01,2022-07-01 23:55:55,1,NaN,25.0
46738,24824,620,0,86912440,MALBORA RED LONG,1,29.0,29.0,2022-07-01,2022-07-01 23:56:03,1,NaN,25.0

In [5]:
df.shape

(44055, 13)

In [6]:
df = df.reset_index(drop = True)

In [7]:
# sütun silme
df = df.drop("musteriid", axis = 1)

In [8]:
df.tail()

,satisid,urunid,barkodno,urunadi,satisadet,satisfiyati,toplamsatis,satistarihi,satistarihi2,personelid,satisnot,firmaid
44050,24820,200,8690637878077,ALGİDA KEYİF 750 ML VİŞNE LİMON,1,20.0,20.0,2022-07-01,2022-07-01 23:49:04,1,NaN,1.0
44051,24821,4162,90162848,RED BUL ŞEKERSİZ 250 ML,2,15.0,30.0,2022-07-01,2022-07-01 23:55:38,1,NaN,27.0
44052,24822,623,86935258,MALBORA TOUCH GRAY,1,28.0,28.0,2022-07-01,2022-07-01 23:55:49,1,NaN,25.0
44053,24823,618,86937757,MALBORA EDGE BULUE,1,27.0,27.0,2022-07-01,2022-07-01 23:55:55,1,NaN,25.0
44054,24824,620,86912440,MALBORA RED LONG,1,29.0,29.0,2022-07-01,2022-07-01 23:56:03,1,NaN,25.0

In [9]:
df.dtypes

satisid                  int64
urunid                   int64
barkodno                object
urunadi                 object
satisadet                int64
satisfiyati            float64
toplamsatis            float64
satistarihi     datetime64[ns]
satistarihi2    datetime64[ns]
personelid               int64
satisnot               float64
firmaid                float64
dtype: object

In [9]:
from datetime import datetime

In [10]:
x = [datetime(2022,1,5), datetime(2022,1,7)]
zs = pd.Series([5,7], index = x)
zs

2022-01-05    5
2022-01-07    7
dtype: int64

In [11]:
tarih = []

for i in range(len(df)):
    tarih.append(df.satistarihi[i])

In [12]:
len(tarih)

44055

In [13]:
new_df = df
new_df.index = tarih
new_df

,satisid,urunid,barkodno,urunadi,satisadet,satisfiyati,toplamsatis,satistarihi,satistarihi2,personelid,satisnot,firmaid
2022-11-06,74195,4191,5449000189356,FUSE TEA 1 L MANGO ANANAS,1,12.5,12.5,2022-11-06,2022-11-06 00:01:11,3,NaN,12.0
2022-11-06,74196,4672,8690504067108,ÜLKER KEKSRA JÖLEBOL ÇİLEKLİ (40G),1,3.5,3.5,2022-11-06,2022-11-06 00:01:16,3,NaN,34.0
2022-11-06,74197,4171,8690526074238,ETİ KRAX DAHA BAHARATLI,1,4.0,4.0,2022-11-06,2022-11-06 00:01:19,3,NaN,15.0
2022-11-06,74198,60,8690504027508,ÜLKER ÇOKANAT,1,5.0,5.0,2022-11-06,2022-11-06 00:01:22,3,NaN,34.0
2022-11-06,74199,4040,8690504009542,ÜLKER ÇİZİ VİÇ,1,7.5,7.5,2022-11-06,2022-11-06 00:01:24,3,NaN,34.0
...,...,...,...,...,...,...,...,...,...,...,...,...
2022-07-01,24820,200,8690637878077,ALGİDA KEYİF 750 ML VİŞNE LİMON,1,20.0,20.0,2022-07-01,2022-07-01 23:49:04,1,NaN,1.0
2022-07-01,24821,4162,90162848,RED BUL ŞEKERSİZ 250 ML,2,15.0,30.0,2022-07-01,2022-07-01 23:55:38,1,NaN,27.0
2022-07-01,24822,623,86935258,MALBORA TOUCH GRAY,1,28.0,28.0,2022-07-01,2022-07-01 23:55:49,1,NaN,25.0
2022-07-01,24823,618,86937757,MALBORA EDGE BULUE,1,27.0,27.0,2022-07-01,2022-07-01 23:55:55,1,NaN,25.0
2022-07-01,24824,620,86912440,MALBORA RED LONG,1,29.0,29.0,2022-07-01,2022-07-01 23:56:03,1,NaN,25.0

In [14]:
new_df = new_df.drop(["satistarihi", "satistarihi2", "satisnot"],axis = 1)
new_df

,satisid,urunid,barkodno,urunadi,satisadet,satisfiyati,toplamsatis,personelid,firmaid
2022-11-06,74195,4191,5449000189356,FUSE TEA 1 L MANGO ANANAS,1,12.5,12.5,3,12.0
2022-11-06,74196,4672,8690504067108,ÜLKER KEKSRA JÖLEBOL ÇİLEKLİ (40G),1,3.5,3.5,3,34.0
2022-11-06,74197,4171,8690526074238,ETİ KRAX DAHA BAHARATLI,1,4.0,4.0,3,15.0
2022-11-06,74198,60,8690504027508,ÜLKER ÇOKANAT,1,5.0,5.0,3,34.0
2022-11-06,74199,4040,8690504009542,ÜLKER ÇİZİ VİÇ,1,7.5,7.5,3,34.0
...,...,...,...,...,...,...,...,...,...
2022-07-01,24820,200,8690637878077,ALGİDA KEYİF 750 ML VİŞNE LİMON,1,20.0,20.0,1,1.0
2022-07-01,24821,4162,90162848,RED BUL ŞEKERSİZ 250 ML,2,15.0,30.0,1,27.0
2022-07-01,24822,623,86935258,MALBORA TOUCH GRAY,1,28.0,28.0,1,25.0
2022-07-01,24823,618,86937757,MALBORA EDGE BULUE,1,27.0,27.0,1,25.0
2022-07-01,24824,620,86912440,MALBORA RED LONG,1,29.0,29.0,1,25.0

In [15]:
# Gün bazında veriyi okuma ve toplam satışı bulma
day_1106 = new_df["2022-11-05"]
day_1106.toplamsatis.sum()

C:\Users\Murat\AppData\Local\Temp/ipykernel_396/1299527593.py:2: FutureWarning: Indexing a DataFrame with a datetimelike index using a single string to slice the rows, like `frame[string]`, is deprecated and will be removed in a future version. Use `frame.loc[string]` instead.
  day_1106 = new_df["2022-11-05"]

7982.0

In [18]:
# Gün bazında veriyi okuma ve toplam satışı bulmak için daha kısa yol
new_df["2022-11-05"].toplamsatis.sum()

C:\Users\Murat\AppData\Local\Temp/ipykernel_12940/1445647997.py:2: FutureWarning: Indexing a DataFrame with a datetimelike index using a single string to slice the rows, like `frame[string]`, is deprecated and will be removed in a future version. Use `frame.loc[string]` instead.
  new_df["2022-11-05"].toplamsatis.sum()

7982.0

In [16]:
fiyatList = []

fiyatList.append(new_df["2022-11-05"].toplamsatis.sum())
fiyatList.append(new_df["2022-11-04"].toplamsatis.sum())
fiyatList.append(new_df["2022-11-03"].toplamsatis.sum())
fiyatList.append(new_df["2022-11-02"].toplamsatis.sum())
fiyatList.append(new_df["2022-11-01"].toplamsatis.sum())


fiyatList.append(new_df["2022-10-31"].toplamsatis.sum())
fiyatList.append(new_df["2022-10-30"].toplamsatis.sum())
fiyatList.append(new_df["2022-10-29"].toplamsatis.sum())
fiyatList.append(new_df["2022-10-28"].toplamsatis.sum())
fiyatList.append(new_df["2022-10-27"].toplamsatis.sum())
fiyatList.append(new_df["2022-10-26"].toplamsatis.sum())
fiyatList.append(new_df["2022-10-25"].toplamsatis.sum())
fiyatList.append(new_df["2022-10-24"].toplamsatis.sum())
fiyatList.append(new_df["2022-10-23"].toplamsatis.sum())
fiyatList.append(new_df["2022-10-22"].toplamsatis.sum())
fiyatList.append(new_df["2022-10-21"].toplamsatis.sum())
fiyatList.append(new_df["2022-10-20"].toplamsatis.sum())
fiyatList.append(new_df["2022-10-19"].toplamsatis.sum())
fiyatList.append(new_df["2022-10-18"].toplamsatis.sum())
fiyatList.append(new_df["2022-10-17"].toplamsatis.sum())
fiyatList.append(new_df["2022-10-16"].toplamsatis.sum())
fiyatList.append(new_df["2022-10-15"].toplamsatis.sum())
fiyatList.append(new_df["2022-10-14"].toplamsatis.sum())
fiyatList.append(new_df["2022-10-13"].toplamsatis.sum())
fiyatList.append(new_df["2022-10-12"].toplamsatis.sum())
fiyatList.append(new_df["2022-10-11"].toplamsatis.sum())
fiyatList.append(new_df["2022-10-10"].toplamsatis.sum())
fiyatList.append(new_df["2022-10-09"].toplamsatis.sum())
fiyatList.append(new_df["2022-10-08"].toplamsatis.sum())
fiyatList.append(new_df["2022-10-07"].toplamsatis.sum())
fiyatList.append(new_df["2022-10-06"].toplamsatis.sum())
fiyatList.append(new_df["2022-10-05"].toplamsatis.sum())
fiyatList.append(new_df["2022-10-04"].toplamsatis.sum())
fiyatList.append(new_df["2022-10-03"].toplamsatis.sum())
fiyatList.append(new_df["2022-10-02"].toplamsatis.sum())
fiyatList.append(new_df["2022-10-01"].toplamsatis.sum())


fiyatList.append(new_df["2022-09-30"].toplamsatis.sum())
fiyatList.append(new_df["2022-09-29"].toplamsatis.sum())
fiyatList.append(new_df["2022-09-28"].toplamsatis.sum())
fiyatList.append(new_df["2022-09-27"].toplamsatis.sum())
fiyatList.append(new_df["2022-09-26"].toplamsatis.sum())
fiyatList.append(new_df["2022-09-25"].toplamsatis.sum())
fiyatList.append(new_df["2022-09-24"].toplamsatis.sum())
fiyatList.append(new_df["2022-09-23"].toplamsatis.sum())
fiyatList.append(new_df["2022-09-22"].toplamsatis.sum())
fiyatList.append(new_df["2022-09-21"].toplamsatis.sum())
fiyatList.append(new_df["2022-09-20"].toplamsatis.sum())
fiyatList.append(new_df["2022-09-19"].toplamsatis.sum())
fiyatList.append(new_df["2022-09-18"].toplamsatis.sum())
fiyatList.append(new_df["2022-09-17"].toplamsatis.sum())
fiyatList.append(new_df["2022-09-16"].toplamsatis.sum())
fiyatList.append(new_df["2022-09-15"].toplamsatis.sum())
fiyatList.append(new_df["2022-09-14"].toplamsatis.sum())
fiyatList.append(new_df["2022-09-13"].toplamsatis.sum())
fiyatList.append(new_df["2022-09-12"].toplamsatis.sum())
fiyatList.append(new_df["2022-09-11"].toplamsatis.sum())
fiyatList.append(new_df["2022-09-10"].toplamsatis.sum())
fiyatList.append(new_df["2022-09-09"].toplamsatis.sum())
fiyatList.append(new_df["2022-09-08"].toplamsatis.sum())
fiyatList.append(new_df["2022-09-07"].toplamsatis.sum())
fiyatList.append(new_df["2022-09-06"].toplamsatis.sum())
fiyatList.append(new_df["2022-09-05"].toplamsatis.sum())
fiyatList.append(new_df["2022-09-04"].toplamsatis.sum())
fiyatList.append(new_df["2022-09-03"].toplamsatis.sum())
fiyatList.append(new_df["2022-09-02"].toplamsatis.sum())
fiyatList.append(new_df["2022-09-01"].toplamsatis.sum())


fiyatList.append(new_df["2022-08-31"].toplamsatis.sum())
fiyatList.append(new_df["2022-08-30"].toplamsatis.sum())
fiyatList.append(new_df["2022-08-29"].toplamsatis.sum())
fiyatList.append(new_df["2022-08-28"].toplamsatis.sum())
fiyatList.append(new_df["2022-08-27"].toplamsatis.sum())
fiyatList.append(new_df["2022-08-26"].toplamsatis.sum())
fiyatList.append(new_df["2022-08-25"].toplamsatis.sum())
fiyatList.append(new_df["2022-08-24"].toplamsatis.sum())
fiyatList.append(new_df["2022-08-23"].toplamsatis.sum())
fiyatList.append(new_df["2022-08-22"].toplamsatis.sum())
fiyatList.append(new_df["2022-08-21"].toplamsatis.sum())
fiyatList.append(new_df["2022-08-20"].toplamsatis.sum())
fiyatList.append(new_df["2022-08-19"].toplamsatis.sum())
fiyatList.append(new_df["2022-08-18"].toplamsatis.sum())
fiyatList.append(new_df["2022-08-17"].toplamsatis.sum())
fiyatList.append(new_df["2022-08-16"].toplamsatis.sum())
fiyatList.append(new_df["2022-08-15"].toplamsatis.sum())
fiyatList.append(new_df["2022-08-14"].toplamsatis.sum())
fiyatList.append(new_df["2022-08-13"].toplamsatis.sum())
fiyatList.append(new_df["2022-08-12"].toplamsatis.sum())
fiyatList.append(new_df["2022-08-11"].toplamsatis.sum())
fiyatList.append(new_df["2022-08-10"].toplamsatis.sum())
fiyatList.append(new_df["2022-08-09"].toplamsatis.sum())
fiyatList.append(new_df["2022-08-08"].toplamsatis.sum())
fiyatList.append(new_df["2022-08-07"].toplamsatis.sum())
fiyatList.append(new_df["2022-08-06"].toplamsatis.sum())
fiyatList.append(new_df["2022-08-05"].toplamsatis.sum())
fiyatList.append(new_df["2022-08-04"].toplamsatis.sum())
fiyatList.append(new_df["2022-08-03"].toplamsatis.sum())
fiyatList.append(new_df["2022-08-02"].toplamsatis.sum())
fiyatList.append(new_df["2022-08-01"].toplamsatis.sum())


fiyatList.append(new_df["2022-07-31"].toplamsatis.sum())
fiyatList.append(new_df["2022-07-30"].toplamsatis.sum())
fiyatList.append(new_df["2022-07-29"].toplamsatis.sum())
fiyatList.append(new_df["2022-07-28"].toplamsatis.sum())
fiyatList.append(new_df["2022-07-27"].toplamsatis.sum())
fiyatList.append(new_df["2022-07-26"].toplamsatis.sum())
fiyatList.append(new_df["2022-07-25"].toplamsatis.sum())
fiyatList.append(new_df["2022-07-24"].toplamsatis.sum())
fiyatList.append(new_df["2022-07-23"].toplamsatis.sum())
fiyatList.append(new_df["2022-07-22"].toplamsatis.sum())
fiyatList.append(new_df["2022-07-21"].toplamsatis.sum())
fiyatList.append(new_df["2022-07-20"].toplamsatis.sum())
fiyatList.append(new_df["2022-07-19"].toplamsatis.sum())
fiyatList.append(new_df["2022-07-18"].toplamsatis.sum())
fiyatList.append(new_df["2022-07-17"].toplamsatis.sum())
fiyatList.append(new_df["2022-07-16"].toplamsatis.sum())
fiyatList.append(new_df["2022-07-15"].toplamsatis.sum())
fiyatList.append(new_df["2022-07-14"].toplamsatis.sum())
fiyatList.append(new_df["2022-07-13"].toplamsatis.sum())
fiyatList.append(new_df["2022-07-12"].toplamsatis.sum())
fiyatList.append(new_df["2022-07-11"].toplamsatis.sum())
fiyatList.append(new_df["2022-07-10"].toplamsatis.sum())
fiyatList.append(new_df["2022-07-09"].toplamsatis.sum())
fiyatList.append(new_df["2022-07-08"].toplamsatis.sum())
fiyatList.append(new_df["2022-07-07"].toplamsatis.sum())
fiyatList.append(new_df["2022-07-06"].toplamsatis.sum())
fiyatList.append(new_df["2022-07-05"].toplamsatis.sum())
fiyatList.append(new_df["2022-07-04"].toplamsatis.sum())
fiyatList.append(new_df["2022-07-03"].toplamsatis.sum())
fiyatList.append(new_df["2022-07-02"].toplamsatis.sum())
fiyatList.append(new_df["2022-07-01"].toplamsatis.sum())

C:\Users\Murat\AppData\Local\Temp/ipykernel_396/1461308030.py:3: FutureWarning: Indexing a DataFrame with a datetimelike index using a single string to slice the rows, like `frame[string]`, is deprecated and will be removed in a future version. Use `frame.loc[string]` instead.
  fiyatList.append(new_df["2022-11-05"].toplamsatis.sum())
C:\Users\Murat\AppData\Local\Temp/ipykernel_396/1461308030.py:4: FutureWarning: Indexing a DataFrame with a datetimelike index using a single string to slice the rows, like `frame[string]`, is deprecated and will be removed in a future version. Use `frame.loc[string]` instead.
  fiyatList.append(new_df["2022-11-04"].toplamsatis.sum())
C:\Users\Murat\AppData\Local\Temp/ipykernel_396/1461308030.py:5: FutureWarning: Indexing a DataFrame with a datetimelike index using a single string to slice the rows, like `frame[string]`, is deprecated and will be removed in a future version. Use `frame.loc[string]` instead.
  fiyatList.append(new_df["2022-11-03"].toplamsatis.sum())
C:\Users\Murat\AppData\Local\Temp/ipykernel_396/1461308030.py:6: FutureWarning: Indexing a DataFrame with a datetimelike index using a single string to slice the rows, like `frame[string]`, is deprecated and will be removed in a future version. Use `frame.loc[string]` instead.
  fiyatList.append(new_df["2022-11-02"].toplamsatis.sum())
C:\Users\Murat\AppData\Local\Temp/ipykernel_396/1461308030.py:7: FutureWarning: Indexing a DataFrame with a datetimelike index using a single string to slice the rows, like `frame[string]`, is deprecated and will be removed in a future version. Use `frame.loc[string]` instead.
  fiyatList.append(new_df["2022-11-01"].toplamsatis.sum())
C:\Users\Murat\AppData\Local\Temp/ipykernel_396/1461308030.py:10: FutureWarning: Indexing a DataFrame with a datetimelike index using a single string to slice the rows, like `frame[string]`, is deprecated and will be removed in a future version. Use `frame.loc[string]` instead.
  fiyatList.append(new_df["2022-10-31"].toplamsatis.sum())
C:\Users\Murat\AppData\Local\Temp/ipykernel_396/1461308030.py:11: FutureWarning: Indexing a DataFrame with a datetimelike index using a single string to slice the rows, like `frame[string]`, is deprecated and will be removed in a future version. Use `frame.loc[string]` instead.
  fiyatList.append(new_df["2022-10-30"].toplamsatis.sum())
C:\Users\Murat\AppData\Local\Temp/ipykernel_396/1461308030.py:12: FutureWarning: Indexing a DataFrame with a datetimelike index using a single string to slice the rows, like `frame[string]`, is deprecated and will be removed in a future version. Use `frame.loc[string]` instead.
  fiyatList.append(new_df["2022-10-29"].toplamsatis.sum())
C:\Users\Murat\AppData\Local\Temp/ipykernel_396/1461308030.py:13: FutureWarning: Indexing a DataFrame with a datetimelike index using a single string to slice the rows, like `frame[string]`, is deprecated and will be removed in a future version. Use `frame.loc[string]` instead.
  fiyatList.append(new_df["2022-10-28"].toplamsatis.sum())
C:\Users\Murat\AppData\Local\Temp/ipykernel_396/1461308030.py:14: FutureWarning: Indexing a DataFrame with a datetimelike index using a single string to slice the rows, like `frame[string]`, is deprecated and will be removed in a future version. Use `frame.loc[string]` instead.
  fiyatList.append(new_df["2022-10-27"].toplamsatis.sum())
C:\Users\Murat\AppData\Local\Temp/ipykernel_396/1461308030.py:15: FutureWarning: Indexing a DataFrame with a datetimelike index using a single string to slice the rows, like `frame[string]`, is deprecated and will be removed in a future version. Use `frame.loc[string]` instead.
  fiyatList.append(new_df["2022-10-26"].toplamsatis.sum())
C:\Users\Murat\AppData\Local\Temp/ipykernel_396/1461308030.py:16: FutureWarning: Indexing a DataFrame with a datetimelike index using a single string to slice the rows, like `frame[string]`, is deprecated and will be removed in a future version. Use `frame.loc[string]` instead.
  fiyatList.append(new_df["2022-10-25"].toplamsatis.sum())
C:\Users\Murat\AppData\Local\Temp/ipykernel_396/1461308030.py:17: FutureWarning: Indexing a DataFrame with a datetimelike index using a single string to slice the rows, like `frame[string]`, is deprecated and will be removed in a future version. Use `frame.loc[string]` instead.
  fiyatList.append(new_df["2022-10-24"].toplamsatis.sum())
C:\Users\Murat\AppData\Local\Temp/ipykernel_396/1461308030.py:18: FutureWarning: Indexing a DataFrame with a datetimelike index using a single string to slice the rows, like `frame[string]`, is deprecated and will be removed in a future version. Use `frame.loc[string]` instead.
  fiyatList.append(new_df["2022-10-23"].toplamsatis.sum())
C:\Users\Murat\AppData\Local\Temp/ipykernel_396/1461308030.py:19: FutureWarning: Indexing a DataFrame with a datetimelike index using a single string to slice the rows, like `frame[string]`, is deprecated and will be removed in a future version. Use `frame.loc[string]` instead.
  fiyatList.append(new_df["2022-10-22"].toplamsatis.sum())
C:\Users\Murat\AppData\Local\Temp/ipykernel_396/1461308030.py:20: FutureWarning: Indexing a DataFrame with a datetimelike index using a single string to slice the rows, like `frame[string]`, is deprecated and will be removed in a future version. Use `frame.loc[string]` instead.
  fiyatList.append(new_df["2022-10-21"].toplamsatis.sum())
C:\Users\Murat\AppData\Local\Temp/ipykernel_396/1461308030.py:21: FutureWarning: Indexing a DataFrame with a datetimelike index using a single string to slice the rows, like `frame[string]`, is deprecated and will be removed in a future version. Use `frame.loc[string]` instead.
  fiyatList.append(new_df["2022-10-20"].toplamsatis.sum())
C:\Users\Murat\AppData\Local\Temp/ipykernel_396/1461308030.py:22: FutureWarning: Indexing a DataFrame with a datetimelike index using a single string to slice the rows, like `frame[string]`, is deprecated and will be removed in a future version. Use `frame.loc[string]` instead.
  fiyatList.append(new_df["2022-10-19"].toplamsatis.sum())
C:\Users\Murat\AppData\Local\Temp/ipykernel_396/1461308030.py:23: FutureWarning: Indexing a DataFrame with a datetimelike index using a single string to slice the rows, like `frame[string]`, is deprecated and will be removed in a future version. Use `frame.loc[string]` instead.
  fiyatList.append(new_df["2022-10-18"].toplamsatis.sum())
C:\Users\Murat\AppData\Local\Temp/ipykernel_396/1461308030.py:24: FutureWarning: Indexing a DataFrame with a datetimelike index using a single string to slice the rows, like `frame[string]`, is deprecated and will be removed in a future version. Use `frame.loc[string]` instead.
  fiyatList.append(new_df["2022-10-17"].toplamsatis.sum())
C:\Users\Murat\AppData\Local\Temp/ipykernel_396/1461308030.py:25: FutureWarning: Indexing a DataFrame with a datetimelike index using a single string to slice the rows, like `frame[string]`, is deprecated and will be removed in a future version. Use `frame.loc[string]` instead.
  fiyatList.append(new_df["2022-10-16"].toplamsatis.sum())
C:\Users\Murat\AppData\Local\Temp/ipykernel_396/1461308030.py:26: FutureWarning: Indexing a DataFrame with a datetimelike index using a single string to slice the rows, like `frame[string]`, is deprecated and will be removed in a future version. Use `frame.loc[string]` instead.
  fiyatList.append(new_df["2022-10-15"].toplamsatis.sum())
C:\Users\Murat\AppData\Local\Temp/ipykernel_396/1461308030.py:27: FutureWarning: Indexing a DataFrame with a datetimelike index using a single string to slice the rows, like `frame[string]`, is deprecated and will be removed in a future version. Use `frame.loc[string]` instead.
  fiyatList.append(new_df["2022-10-14"].toplamsatis.sum())
C:\Users\Murat\AppData\Local\Temp/ipykernel_396/1461308030.py:28: FutureWarning: Indexing a DataFrame with a datetimelike index using a single string to slice the rows, like `frame[string]`, is deprecated and will be removed in a future version. Use `frame.loc[string]` instead.
  fiyatList.append(new_df["2022-10-13"].toplamsatis.sum())
C:\Users\Murat\AppData\Local\Temp/ipykernel_396/1461308030.py:29: FutureWarning: Indexing a DataFrame with a datetimelike index using a single string to slice the rows, like `frame[string]`, is deprecated and will be removed in a future version. Use `frame.loc[string]` instead.
  fiyatList.append(new_df["2022-10-12"].toplamsatis.sum())
C:\Users\Murat\AppData\Local\Temp/ipykernel_396/1461308030.py:30: FutureWarning: Indexing a DataFrame with a datetimelike index using a single string to slice the rows, like `frame[string]`, is deprecated and will be removed in a future version. Use `frame.loc[string]` instead.
  fiyatList.append(new_df["2022-10-11"].toplamsatis.sum())
C:\Users\Murat\AppData\Local\Temp/ipykernel_396/1461308030.py:31: FutureWarning: Indexing a DataFrame with a datetimelike index using a single string to slice the rows, like `frame[string]`, is deprecated and will be removed in a future version. Use `frame.loc[string]` instead.
  fiyatList.append(new_df["2022-10-10"].toplamsatis.sum())
C:\Users\Murat\AppData\Local\Temp/ipykernel_396/1461308030.py:32: FutureWarning: Indexing a DataFrame with a datetimelike index using a single string to slice the rows, like `frame[string]`, is deprecated and will be removed in a future version. Use `frame.loc[string]` instead.
  fiyatList.append(new_df["2022-10-09"].toplamsatis.sum())
C:\Users\Murat\AppData\Local\Temp/ipykernel_396/1461308030.py:33: FutureWarning: Indexing a DataFrame with a datetimelike index using a single string to slice the rows, like `frame[string]`, is deprecated and will be removed in a future version. Use `frame.loc[string]` instead.
  fiyatList.append(new_df["2022-10-08"].toplamsatis.sum())
C:\Users\Murat\AppData\Local\Temp/ipykernel_396/1461308030.py:34: FutureWarning: Indexing a DataFrame with a datetimelike index using a single string to slice the rows, like `frame[string]`, is deprecated and will be removed in a future version. Use `frame.loc[string]` instead.
  fiyatList.append(new_df["2022-10-07"].toplamsatis.sum())
C:\Users\Murat\AppData\Local\Temp/ipykernel_396/1461308030.py:35: FutureWarning: Indexing a DataFrame with a datetimelike index using a single string to slice the rows, like `frame[string]`, is deprecated and will be removed in a future version. Use `frame.loc[string]` instead.
  fiyatList.append(new_df["2022-10-06"].toplamsatis.sum())
C:\Users\Murat\AppData\Local\Temp/ipykernel_396/1461308030.py:36: FutureWarning: Indexing a DataFrame with a datetimelike index using a single string to slice the rows, like `frame[string]`, is deprecated and will be removed in a future version. Use `frame.loc[string]` instead.
  fiyatList.append(new_df["2022-10-05"].toplamsatis.sum())
C:\Users\Murat\AppData\Local\Temp/ipykernel_396/1461308030.py:37: FutureWarning: Indexing a DataFrame with a datetimelike index using a single string to slice the rows, like `frame[string]`, is deprecated and will be removed in a future version. Use `frame.loc[string]` instead.
  fiyatList.append(new_df["2022-10-04"].toplamsatis.sum())
C:\Users\Murat\AppData\Local\Temp/ipykernel_396/1461308030.py:38: FutureWarning: Indexing a DataFrame with a datetimelike index using a single string to slice the rows, like `frame[string]`, is deprecated and will be removed in a future version. Use `frame.loc[string]` instead.
  fiyatList.append(new_df["2022-10-03"].toplamsatis.sum())
C:\Users\Murat\AppData\Local\Temp/ipykernel_396/1461308030.py:39: FutureWarning: Indexing a DataFrame with a datetimelike index using a single string to slice the rows, like `frame[string]`, is deprecated and will be removed in a future version. Use `frame.loc[string]` instead.
  fiyatList.append(new_df["2022-10-02"].toplamsatis.sum())
C:\Users\Murat\AppData\Local\Temp/ipykernel_396/1461308030.py:40: FutureWarning: Indexing a DataFrame with a datetimelike index using a single string to slice the rows, like `frame[string]`, is deprecated and will be removed in a future version. Use `frame.loc[string]` instead.
  fiyatList.append(new_df["2022-10-01"].toplamsatis.sum())
C:\Users\Murat\AppData\Local\Temp/ipykernel_396/1461308030.py:43: FutureWarning: Indexing a DataFrame with a datetimelike index using a single string to slice the rows, like `frame[string]`, is deprecated and will be removed in a future version. Use `frame.loc[string]` instead.
  fiyatList.append(new_df["2022-09-30"].toplamsatis.sum())
C:\Users\Murat\AppData\Local\Temp/ipykernel_396/1461308030.py:44: FutureWarning: Indexing a DataFrame with a datetimelike index using a single string to slice the rows, like `frame[string]`, is deprecated and will be removed in a future version. Use `frame.loc[string]` instead.
  fiyatList.append(new_df["2022-09-29"].toplamsatis.sum())
C:\Users\Murat\AppData\Local\Temp/ipykernel_396/1461308030.py:45: FutureWarning: Indexing a DataFrame with a datetimelike index using a single string to slice the rows, like `frame[string]`, is deprecated and will be removed in a future version. Use `frame.loc[string]` instead.
  fiyatList.append(new_df["2022-09-28"].toplamsatis.sum())
C:\Users\Murat\AppData\Local\Temp/ipykernel_396/1461308030.py:46: FutureWarning: Indexing a DataFrame with a datetimelike index using a single string to slice the rows, like `frame[string]`, is deprecated and will be removed in a future version. Use `frame.loc[string]` instead.
  fiyatList.append(new_df["2022-09-27"].toplamsatis.sum())
C:\Users\Murat\AppData\Local\Temp/ipykernel_396/1461308030.py:47: FutureWarning: Indexing a DataFrame with a datetimelike index using a single string to slice the rows, like `frame[string]`, is deprecated and will be removed in a future version. Use `frame.loc[string]` instead.
  fiyatList.append(new_df["2022-09-26"].toplamsatis.sum())
C:\Users\Murat\AppData\Local\Temp/ipykernel_396/1461308030.py:48: FutureWarning: Indexing a DataFrame with a datetimelike index using a single string to slice the rows, like `frame[string]`, is deprecated and will be removed in a future version. Use `frame.loc[string]` instead.
  fiyatList.append(new_df["2022-09-25"].toplamsatis.sum())
C:\Users\Murat\AppData\Local\Temp/ipykernel_396/1461308030.py:49: FutureWarning: Indexing a DataFrame with a datetimelike index using a single string to slice the rows, like `frame[string]`, is deprecated and will be removed in a future version. Use `frame.loc[string]` instead.
  fiyatList.append(new_df["2022-09-24"].toplamsatis.sum())
C:\Users\Murat\AppData\Local\Temp/ipykernel_396/1461308030.py:50: FutureWarning: Indexing a DataFrame with a datetimelike index using a single string to slice the rows, like `frame[string]`, is deprecated and will be removed in a future version. Use `frame.loc[string]` instead.
  fiyatList.append(new_df["2022-09-23"].toplamsatis.sum())
C:\Users\Murat\AppData\Local\Temp/ipykernel_396/1461308030.py:51: FutureWarning: Indexing a DataFrame with a datetimelike index using a single string to slice the rows, like `frame[string]`, is deprecated and will be removed in a future version. Use `frame.loc[string]` instead.
  fiyatList.append(new_df["2022-09-22"].toplamsatis.sum())
C:\Users\Murat\AppData\Local\Temp/ipykernel_396/1461308030.py:52: FutureWarning: Indexing a DataFrame with a datetimelike index using a single string to slice the rows, like `frame[string]`, is deprecated and will be removed in a future version. Use `frame.loc[string]` instead.
  fiyatList.append(new_df["2022-09-21"].toplamsatis.sum())
C:\Users\Murat\AppData\Local\Temp/ipykernel_396/1461308030.py:53: FutureWarning: Indexing a DataFrame with a datetimelike index using a single string to slice the rows, like `frame[string]`, is deprecated and will be removed in a future version. Use `frame.loc[string]` instead.
  fiyatList.append(new_df["2022-09-20"].toplamsatis.sum())
C:\Users\Murat\AppData\Local\Temp/ipykernel_396/1461308030.py:54: FutureWarning: Indexing a DataFrame with a datetimelike index using a single string to slice the rows, like `frame[string]`, is deprecated and will be removed in a future version. Use `frame.loc[string]` instead.
  fiyatList.append(new_df["2022-09-19"].toplamsatis.sum())
C:\Users\Murat\AppData\Local\Temp/ipykernel_396/1461308030.py:55: FutureWarning: Indexing a DataFrame with a datetimelike index using a single string to slice the rows, like `frame[string]`, is deprecated and will be removed in a future version. Use `frame.loc[string]` instead.
  fiyatList.append(new_df["2022-09-18"].toplamsatis.sum())
C:\Users\Murat\AppData\Local\Temp/ipykernel_396/1461308030.py:56: FutureWarning: Indexing a DataFrame with a datetimelike index using a single string to slice the rows, like `frame[string]`, is deprecated and will be removed in a future version. Use `frame.loc[string]` instead.
  fiyatList.append(new_df["2022-09-17"].toplamsatis.sum())
C:\Users\Murat\AppData\Local\Temp/ipykernel_396/1461308030.py:57: FutureWarning: Indexing a DataFrame with a datetimelike index using a single string to slice the rows, like `frame[string]`, is deprecated and will be removed in a future version. Use `frame.loc[string]` instead.
  fiyatList.append(new_df["2022-09-16"].toplamsatis.sum())
C:\Users\Murat\AppData\Local\Temp/ipykernel_396/1461308030.py:58: FutureWarning: Indexing a DataFrame with a datetimelike index using a single string to slice the rows, like `frame[string]`, is deprecated and will be removed in a future version. Use `frame.loc[string]` instead.
  fiyatList.append(new_df["2022-09-15"].toplamsatis.sum())
C:\Users\Murat\AppData\Local\Temp/ipykernel_396/1461308030.py:59: FutureWarning: Indexing a DataFrame with a datetimelike index using a single string to slice the rows, like `frame[string]`, is deprecated and will be removed in a future version. Use `frame.loc[string]` instead.
  fiyatList.append(new_df["2022-09-14"].toplamsatis.sum())
C:\Users\Murat\AppData\Local\Temp/ipykernel_396/1461308030.py:60: FutureWarning: Indexing a DataFrame with a datetimelike index using a single string to slice the rows, like `frame[string]`, is deprecated and will be removed in a future version. Use `frame.loc[string]` instead.
  fiyatList.append(new_df["2022-09-13"].toplamsatis.sum())
C:\Users\Murat\AppData\Local\Temp/ipykernel_396/1461308030.py:61: FutureWarning: Indexing a DataFrame with a datetimelike index using a single string to slice the rows, like `frame[string]`, is deprecated and will be removed in a future version. Use `frame.loc[string]` instead.
  fiyatList.append(new_df["2022-09-12"].toplamsatis.sum())
C:\Users\Murat\AppData\Local\Temp/ipykernel_396/1461308030.py:62: FutureWarning: Indexing a DataFrame with a datetimelike index using a single string to slice the rows, like `frame[string]`, is deprecated and will be removed in a future version. Use `frame.loc[string]` instead.
  fiyatList.append(new_df["2022-09-11"].toplamsatis.sum())
C:\Users\Murat\AppData\Local\Temp/ipykernel_396/1461308030.py:63: FutureWarning: Indexing a DataFrame with a datetimelike index using a single string to slice the rows, like `frame[string]`, is deprecated and will be removed in a future version. Use `frame.loc[string]` instead.
  fiyatList.append(new_df["2022-09-10"].toplamsatis.sum())
C:\Users\Murat\AppData\Local\Temp/ipykernel_396/1461308030.py:64: FutureWarning: Indexing a DataFrame with a datetimelike index using a single string to slice the rows, like `frame[string]`, is deprecated and will be removed in a future version. Use `frame.loc[string]` instead.
  fiyatList.append(new_df["2022-09-09"].toplamsatis.sum())
C:\Users\Murat\AppData\Local\Temp/ipykernel_396/1461308030.py:65: FutureWarning: Indexing a DataFrame with a datetimelike index using a single string to slice the rows, like `frame[string]`, is deprecated and will be removed in a future version. Use `frame.loc[string]` instead.
  fiyatList.append(new_df["2022-09-08"].toplamsatis.sum())

In [17]:
datesIndex = [pd.date_range("2022-07-01", "2022-11-05")]

def Ters(lst):
    lst.reverse()
    return lst

new_fiyatList = Ters(fiyatList)
new_fiyatList

[4157.75,
 5963.75,
 7818.0,
 6479.25,
 4711.25,
 4848.25,
 5407.25,
 5747.25,
 4118.75,
 5959.25,
 8229.25,
 3954.5,
 7357.0,
 4078.25,
 4217.5,
 6891.5,
 3695.5,
 5738.75,
 4505.75,
 5308.75,
 4892.75,
 5024.5,
 5655.0,
 3236.5,
 5438.25,
 4447.5,
 4370.5,
 4031.75,
 4664.0,
 6808.5,
 3227.75,
 4033.25,
 4612.5,
 5260.75,
 4347.75,
 5602.25,
 6872.25,
 4011.0,
 4783.75,
 5236.25,
 5097.25,
 5733.0,
 5355.255999999999,
 7974.5,
 4197.5,
 5326.75,
 5601.25,
 5680.75,
 6160.253,
 4486.5,
 7107.75,
 4246.25,
 6270.753,
 6075.021,
 5644.5,
 4530.0,
 6764.25,
 6135.503,
 3511.5,
 6347.5,
 6008.75,
 6268.0,
 6013.755999999999,
 5713.75,
 6990.2,
 3723.75,
 4807.25,
 5001.005999999999,
 5423.0,
 4626.005999999999,
 5496.75,
 7626.25,
 4287.0,
 4953.75,
 4746.75,
 5072.75,
 3539.756,
 2664.5,
 2569.25,
 3238.25,
 2770.25,
 4873.25,
 4972.753,
 5329.5,
 7515.5,
 5942.5,
 5867.75,
 7243.75,
 6999.75,
 7828.514999999999,
 6719.005999999999,
 6150.25,
 7896.25,
 7874.253,
 8247.5,
 7478.005999999999,
 6004.5,
 6854.75,
 6992.25,
 6173.75,
 6806.75,
 8856.003,
 7016.259,
 7307.25,
 7650.253,
 8174.005999999999,
 5367.5,
 9020.75,
 9339.0,
 9795.5,
 7711.0,
 8478.5,
 7715.75,
 7839.0,
 7178.5,
 7998.255999999999,
 7275.0,
 6777.25,
 7400.5,
 7326.0,
 7964.75,
 8038.005999999999,
 8366.006,
 7800.5,
 7552.0,
 7540.5,
 7294.5,
 7982.0]

In [18]:
timeDatas = pd.DataFrame(new_fiyatList, index = datesIndex, columns=["Total Satis"])
timeDatas

            Total Satis
2022-07-01      4157.75
2022-07-02      5963.75
2022-07-03      7818.00
2022-07-04      6479.25
2022-07-05      4711.25
...                 ...
2022-11-01      7800.50
2022-11-02      7552.00
2022-11-03      7540.50
2022-11-04      7294.50
2022-11-05      7982.00

[128 rows x 1 columns]

In [19]:
new_df["2022-11-02"].toplamsatis.sum()

C:\Users\Murat\AppData\Local\Temp/ipykernel_396/398785592.py:1: FutureWarning: Indexing a DataFrame with a datetimelike index using a single string to slice the rows, like `frame[string]`, is deprecated and will be removed in a future version. Use `frame.loc[string]` instead.
  new_df["2022-11-02"].toplamsatis.sum()

7552.0

In [26]:
df.head()

,satisid,urunid,barkodno,urunadi,satisadet,satisfiyati,toplamsatis,satistarihi,satistarihi2,personelid,satisnot,firmaid
2022-11-06,74195,4191,5449000189356,FUSE TEA 1 L MANGO ANANAS,1,12.5,12.5,2022-11-06,2022-11-06 00:01:11,3,NaN,12.0
2022-11-06,74196,4672,8690504067108,ÜLKER KEKSRA JÖLEBOL ÇİLEKLİ (40G),1,3.5,3.5,2022-11-06,2022-11-06 00:01:16,3,NaN,34.0
2022-11-06,74197,4171,8690526074238,ETİ KRAX DAHA BAHARATLI,1,4.0,4.0,2022-11-06,2022-11-06 00:01:19,3,NaN,15.0
2022-11-06,74198,60,8690504027508,ÜLKER ÇOKANAT,1,5.0,5.0,2022-11-06,2022-11-06 00:01:22,3,NaN,34.0
2022-11-06,74199,4040,8690504009542,ÜLKER ÇİZİ VİÇ,1,7.5,7.5,2022-11-06,2022-11-06 00:01:24,3,NaN,34.0

In [33]:
x,y,z = pd.date_range(df.satistarihi[1], periods=3, freq="8H")

Timedelta('0 days 08:00:00')

In [36]:
newList = []

for i in range(len(timeDatas)):
    newList.append(pd.date_range(new_df.satistarihi[i], periods = 3, freq="8H"))

In [41]:
newList[13]

DatetimeIndex(['2022-11-06 00:00:00', '2022-11-06 08:00:00',
               '2022-11-06 16:00:00'],
              dtype='datetime64[ns]', freq='8H')